### PR TITLE
Fixing byob TypeError: Constructor TextEncoder requires 'new'

### PR DESCRIPTION
**Pull request by rodms10**
I was seeing a "TypeError: Constructor TextEncoder requires 'new'" exception when trying to build a bundle. Fix was straight forward. `gh-pages` PR coming.

You can see it working at http://rodms10.github.io/brick/download.html

### CODE REVIEW

**Comment by rodms10** [comment]
Note that this does not happen in Firefox release. This broke after a change introduced in Firefox 30 (currently aurora), as you can see [here](https://developer.mozilla.org/en-US/Firefox/Releases/30/Site_Compatibility#DOM_object_constructors_can_no_longer_be_called_as_functions). Chrome Canary has the same problem. The fixed version works both on newer and older browsers.

**Comment by sole** [comment]
Oh, nice! Thanks @rodms10! I'll let @potch or @pennyfx verify all is swell and merge the PR, as they wrote this part.
However, JSZip is an external library-what about submitting a PR to them too? It would make the thing better for everyone! :-)

**Comment by rodms10** [comment]
Thanks @sole! I actually checked their code and the latest version is very different and does not have the same issue.

**Comment by potch** [comment]
if the latest JSZip has this issue fixed, I'm going to try to pull in the latest JSZip to resolve this issue.

**Comment by pennyfx** [comment]
I'm gonna merge these for now.  When we do our 1.1 release we will switch to the new version of JSZip

**Pull request merged**
