### PR TITLE
attempt at implementing vertical slider

### PR DESCRIPTION
**Pull request by SignpostMarv**
Although there's a webkit vendor prefix for making a range slider vertical, there doesn't seem to be a cross-browser implementation.

I've attempt to fudge something into x-slider that would seem to do the trick- it's not perfect, but I'm sure persons more familiar with x-tags than myself could perfect the technique :)

### CODE REVIEW

**Comment by SignpostMarv** [comment]
p.s. practical example under the magnifying glass on http://mapapi.net/secondlife

**Comment by potch** [comment]
Thanks for the Pull Request. @ldoubleuz, could you take a look at this and see whether the approach here or something like it is something we could add to the slider component?

**Comment by SignpostMarv** [comment]
I took perhaps the slightly odd route of using css transform; I'm thinking that either having it rewritten to use a vertical setup without the transform would be the simpler route (I'd already tried using css transforms on input[range] without using x-tags, but found that chrome had issues whilst firefox did not :s

**Comment by ldoubleuz** [comment]
@potch Sure thing, I can definitely look at it this weekend after I've
gotten through this latest batch of coursework. Kind of drowning in work at
the moment. D:

**Comment by SignpostMarv** [comment]
long weekend/more coursework than expected? :P

**Comment by ldoubleuz** [comment]
Yeah, sorry, I have a lot less time this semester than I was expecting. :(

**Comment by potch** [comment]
@SignpostMarv will be looking at this PR this week, and hopefully merging it! Thanks!

**Comment by pennyfx** [comment]
Thanks for the pull request.  Merged here. 
https://github.com/x-tag/slider/commit/25428900b74da1b8c013d0013dd7fa8d079d1a2e

**Pull request closed without merging**
