### PR TITLE
r? Update site design (from @gkoberger)

### LINKED ISSUE #61: Fresh coat of paint
I felt Brick could use a bit of a refresh.

main

Clicking any of the types in "See it in action" would make the demo appear on the actual phone. The code would show up on the right, and any controls ("Flip Me") would show up on the actual UI.

The top bar and the text at the bottom could use a little love, too -- but my 30 minute limit ran out :)

(Here's the PSD: http://cl.ly/1J3f2Z1A0o2r)

### PR DESCRIPTION
**Pull request by tofumatt**
Close #61 with a design based on the mockup + PSD from @gkoberger.

I made some liberties with the conversion, and implemented what I thought
made sense for a responsive design.

---

This is what I have so far, but it's not complete. Hopefully I'm on the right track.

screenshot 2014-03-20 01 15 01

**This is a work-in-progress, not everything is complete yet, especially the responsive bits.**

### CODE REVIEW

**Comment by tofumatt** [comment]
So I like the look of the Firefox OS phone in the mockup, but I think I like the fully HTML phone more, especially as it feels more like an "everyphone" rather than like these are components specifically for Firefox OS.

**Comment by tofumatt** [comment]
Things now look like this:

screenshot 2014-03-20 16 17 27

But I'm unsure what to do with the "toggle flipbox" button. I've been avoiding rewriting the JS to allow it to go inside the phone, especially as that content is rendered out and I like how simple the two `<div>`s look, but I'm at a loss for what to do with it.

### Responsive

Meanwhile, here's the iPad-sized version so far:

screenshot 2014-03-20 16 19 16

(I'm thinking those line lengths are probably too long.)

**Comment by gkoberger** [comment]
Lookin' good!

**Comment by tofumatt** [comment]
Update: this is, in my mind, complete and ready for r?. Attached are screenshots of the changes.

I took the liberty of cleaning up some CSS too, though it's all a bit hairy still.

I removed the phone from the phone-sized views, as it's in the docs and I felt it distracting and hard to work in. I'd like to improve the phone in the future still, including having the toggle switch _in_ the phone and fixing some Safari bugs on it.

### Phone (iPhone, but it's basically similar across phones.)

screenshot 2014-03-28 17 31 54

### Tablet

screenshot 2014-03-28 17 32 02

### Fullscreen

screenshot 2014-03-28 17 31 46

**Comment by tofumatt** [comment]
P.S. I can rebase these commits into one if you want, though I'm not sure if you care; they're reasonably atomic, at least near the end.

**Comment by waldyrious** [comment]
Comparing [both](https://cloud.githubusercontent.com/assets/90871/2555540/ea325b8a-b6c0-11e3-8bd9-df1698c9e4ac.png) [images](https://camo.githubusercontent.com/e5cbdbd95b0f51461c736f41a91017b6afddcb85/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3338313339332f313137383035382f37616630653435342d323139622d313165332d396365362d6338666536353463313366622e706e67) side by side, here are some minor comments:
- the orange is too bright in the html version, I feel a closer shade to the original image would work better. In general the colors seem softer and warmer in the original design.
- the phone is too wide, I think the original design's aspect ratio looks better.
- the shadow under the phone in the original design gave it a nice 3D effect; it could be preserved. A gradient in its fill would be neat, too.

Apart from the above, it looks great! Awesome job :)

**Comment by sole** [comment]
Suppose I just put on my designer hat! 🎩

Can I suggest toning down that orange brickwork? It feels like a placeholder was left behind, and it really clashes with the blue background in the phone screen :-)

Also, there was a bunch of alignments that I noticed. Sorry about the absolutely not elegant at all hand drawn arrows, but I don't have any mouse or tablet, and had to do with the trackpad!
screen shot 2014-03-31 at 11 07 15

I highlighted the things that feel misaligned. Then the three columns below don't seem to be aligned with the rest.

The space between the phone and the rest of the column makes it feel a bit disconnected to the actionable items on the right--how can I know that _Toggle flipbox_ is related to the phone? It seems to belong to the _Download Brick_ hierarchy.

Not sure if it's worth addressing this now or rather iterate on it--I'm open for discussion! :-)

**Comment by fwenzel** [comment]
Good eye sole :+1:

**Comment by fwenzel** [comment]
Also good job so far @tofumatt !

**Comment by tofumatt** [comment]
Here's the new Brick image and some CSS tweaks.
screenshot 2014-04-07 00 47 08

In terms of the alignment of the boxes below, I've stuck to using the classes in the existing grid and what was designed... I'm open to more critiques but maybe those could be iterated upon? I'd love to get this merged in soon if we think it's better :-)

Sooo, r? again?

**Comment by tofumatt** [comment]
Also, here's a slightly more saturated version of the background. Which do people find better? I suck with colour!
screenshot 2014-04-07 00 51 14

**Comment by tofumatt** [comment]
I'd welcome more of @sole's feedback too; I'm really no designer. I just tried to integrate Greg's work as best I could while having it work responsively.

**Comment by waldyrious** [comment]
Are you guys deliberately ignoring feedback from outside of the owner/collaborator clique?

**Comment by tofumatt** [comment]
Hey @waldir, nope. Not my intention, though I know both you and @sole had some issues that I haven't totally addressed. I tried to tone down the orange as you mentioned but as @fwenzel and I discussed last night on IRC, it may be better if someone with more design skills than me (i.e. any!) takes a crack at it.

Re: the phone size: I want to leave it the size it is now as I have it fitting in the grid in various places, but I can get to work on that in a separate PR.

The 3D effect on the phone was through using images, whereas this one is built entirely in HTML/CSS, which I'm going to leave as-is for now.

**Comment by waldyrious** [comment]
I didn't say that because some of my comments weren't addressed (they were just suggestions, after all, which means it's perfectly fine if they were explicitly rejected given sensible reasons). Instead, they weren't even acknowledged! But no hard-feelings, I just wanted to call your attention to how this may look for outside participants.

Regarding the 3D effect, I was planning to give it a try myself using CSS3 shadows, but first I'd need to know whether you guys think it's a good idea, or prefer a flatter design (same goes for the phone size and fill gradient suggestions).

**Comment by potch** [comment]
Tofumatt, you are awesome. Taking a look at this today.

**Comment by tofumatt** [comment]
I updated the templates so things are now Done Proper™.

**Comment by tofumatt** [comment]
Awwww, thanks. :heart:

**Pull request merged**
