### PR TITLE
Removed console.log() and console.warn() calls in most instances. 

### PR DESCRIPTION
**Pull request by JoshStrobl**
This was development-specific code that is no longer necessarily for the production environment.

Worth noting that console.group, console.groupEnd, and any other functions that are called in conjunction with the logFlags.dom property (such as in brick.js) were NOT removed.

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Travis CI build claims fail, yet outputs the following:

PASS 4 tests executed in 2.876s, 4 passed, 0 failed, 0 dubious, 0 skipped.

The failure seems to be a result of one of the following:

```
npm ERR! fetch failed https://registry.npmjs.org/lru-cache/-/lru-cache-2.5.0.tgz
npm ERR! Error: 400 Bad Request
npm ERR!     at WriteStream.<anonymous> (/home/travis/.nvm/v0.10.22/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /home/travis/.nvm/v0.10.22/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 2.6.32-042stab079.5
npm ERR! command "/home/travis/.nvm/v0.10.22/bin/node" "/home/travis/.nvm/v0.10.22/bin/npm" "install"
npm ERR! cwd /home/travis/build/mozilla/brick
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/mozilla/brick/npm-debug.log
npm ERR! not ok code 0
```

```
$ grunt site
grunt-cli: The grunt command line interface. (v0.1.11)
Fatal error: Unable to find local grunt.
If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:
http://gruntjs.com/getting-started
The command "grunt site" exited with 99.
```

**Comment by potch** [comment]
Harumph! Will investigate the travis issue. Might be npm acting up.

**Comment by potch** [comment]
As suspected, an intermittent failure. Thanks for this!

**Comment by potch** [comment]
Oh derp. I just realized that we don't document this very well. We actually keep the code for each component in its own repository, and just build in mozilla/brick. Would you be willing to re-submit to the various repos? They are located in the `x-tag` organization. (for example, https://github.com/x-tag/calendar) I'm happy to manually make these changes over there, but you can also re-submit these PRs if you'd like.

**Comment by JoshStrobl** [comment]
Hey @potch, sorry the delay in a reply. Would you like me to submit the same pull request to each x-tag repo, even though the pull request contains code for other x-tags? If you want me to do a fork of the x-tag repos and individually patch, I'll happily do so, just gotta know!

The pull request would be submitted to:
[x-tag/core](https://github.com/x-tag/core)
[x-tag/calendar](https://github.com/x-tag/calendar)
[x-tag/deck](https://github.com/x-tag/deck)
[x-tag/tooltip](https://github.com/x-tag/tooltip)

**Comment by potch** [comment]
No worries! I've been going through and doing code hygiene cleanup with jshint, and removing these calls along the way. If you want to take a crack at core and tooltip, that would be awesome (haven't done those yet). Thanks!

**Comment by potch** [comment]
Closing this up in favor of commits on individual repos.

**Pull request closed without merging**
