### PR TITLE
Changed normalize function in x-tag-calendar.js

### PR DESCRIPTION
**Pull request by p0ffsrule**
Haven't updated the min.js or the brick.js

### CODE REVIEW

**Comment by fwenzel** [comment]
Thank you for your contribution, but you want to patch the calendar component directly.

Check out the readme about how to develop against the individual component repositories: https://github.com/mozilla/brick#development

**Comment by p0ffsrule** [comment]
Oh.  Sorry for not reading that first.

**Comment by fwenzel** [comment]
No problem! You should be able to just apply the same patch to the x-calendar repository instead.

**Comment by potch** [comment]
closing this up in favor of a an https://github.com/x-tag/calendar PR.

**Pull request closed without merging**
